#!/bin/bash


gcc -g -Wall -c ./xml.c -o ./obj/xml.o

gcc -g -Wall -c ./analysis_soap.c -o ./obj/analysis_soap.o

gcc -g -o analysis_soap_test ./analysis_soap_test.c ./obj/xml.o ./obj/analysis_soap.o
