#!/bin/bash

#gcc -g -Wall -c ../../common/crc8.c -o ./obj/crc8.o -I../../common

#gcc -g -Wall -c ../../common/cJSON.c -o ./obj/cJSON.o -I../../common

#gcc -g -o test test.c ./obj/crc8.o ./obj/cJSON.o -I../../common -lpthread -lm


#rm ./obj/*

gcc clientssl.c -o clientssl -I/usr/include -lssl -lcrypto
